services:
  - type: web
    name: olx-scraper
    env: docker
    plan: free
    region: frankfurt
    autoDeploy: true

    repo: https://github.com/gnez360/olx-scrapper.git
    branch: main
  
    startCommand: "npm start" 
    numInstances: 1
    healthCheckPath: /health
    healthCheckTimeout: 600
    healthCheckInterval: 60
    autoStart: true

    cpu: 0.5
    memory: 512Mi
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    concurrency:
      softLimit: 5
      hardLimit: 10

    dockerfilePath: Dockerfile
