services:
  - type: web
    name: olx-scraper
    env: docker
    plan: free
    region: frankfurt
    autoDeploy: true

    repo: https://github.com/hackhaveli/olx-Scrapper-with-ai.git
    branch: main
  
    numInstances: 1
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: GEMINI_API_KEY
        sync: false

    dockerfilePath: Dockerfile
